import { useMemo } from "react";
import { useSelector } from "react-redux";

export const tokens = (mode) => ({
  ...(mode === "English"
    ? {
        user: {
          admin: "Admin",
          manager: "Manager",
          user: "User",
          400: "#858585",
          500: "#666666",
          600: "#525252",
          700: "#3d3d3d",
          800: "#292929",
          900: "#141414",
        },
        sidebar: {
          overview: "OVERVIEW",
          app: "App",
          commerce: "Commerce",
          files: "Files",
          calendar: "Calendar",
          managment: "Managment",
          list: "List",
          create: "Create",
          800: "#080b12",
          900: "#040509",
        },
        setting: {
          setting: "Settings",
          mode: "Mode",
          contrast: "Contrast",
          direction: "Direction",
          layout: "Layout",
          stretch: "Stretch",
          presets: "Presets",
          api: "API",
          local: "Local",
          global: "Global",
          fullscreen: "Fullscreen",
        },
        song: {
          song: "Song",
          name: "Name",
          singer: "Singer",
          lyrics: "Lyrics",
          image: "Image",
          category: "Category",
          playlist: "Playlist",
          album: "Album",
          tags: "Tags",
          view: "View",
          comment: "Comment",
          published: "Published",
          normal: "Normal",
          yourWork: "Your Work",
          remember: "Remember",
        },
        loginPage: {
          left: "Hi, Welcome back",
          rightTop: "Sign in to Kurdsong",
          rightBottom: "Continue to your accont",
          inputOwn: "Email address",
          inputTwo: "Password",
          button: "Login",
        },
      }
    : mode === "French"
    ? {
        user: {
          admin: "Administratrice",
          manager: "Directrice",
          user: "Utilisatrice",
          300: "#3d3d3d",
          400: "#525252",
          500: "#666666",
          600: "#858585",
          700: "#a3a3a3",
          800: "#c2c2c2",
          900: "#e0e0e0",
        },
        sidebar: {
          overview: "APERÇU",
          app: "App",
          commerce: "Commerce",
          files: "Fichiers",
          calendar: "Calendrier",
          managment: "Gestion",
          list: "Liste",
          create: "Créer",
          700: "#727681",
          800: "#a1a4ab",
          900: "#d0d1d5",
        },
        setting: {
          setting: "Paramètres",
          mode: "Mode",
          contrast: "Contraste",
          direction: "Direction",
          layout: "Mise en page",
          stretch: "Extensible",
          presets: "Préréglages",
          api: "API",
          local: "Locale",
          global: "Mondiale",
          fullscreen: "Plein écran",
        },
        song: {
          song: "Song",
          name: "Name",
          singer: "Singer",
          lyrics: "Lyrics",
          image: "Image",
          category: "Category",
          playlist: "Playlist",
          album: "Album",
          tags: "Tags",
          view: "View",
          comment: "Comment",
          published: "Published",
          normal: "Normal",
          yourWork: "Your Work",
          remember: "Remember",
        },
        loginPage: {
          left: "Bonjour, bon retour",
          rightTop: "Connectez-vous à Kurdsong",
          rightBottom: "Continuez vers votre compte",
          inputOwn: "Adresse email",
          inputTwo: "Mot de passe",
          button: "Se connecter",
        },
      }
    : mode === "Turkish"
    ? {
        user: {
          admin: "Yönetici",
          manager: "Müdür",
          user: "Kullanıcı",
          300: "#3d3d3d",
          400: "#525252",
          500: "#666666",
          600: "#858585",
          700: "#a3a3a3",
          800: "#c2c2c2",
          900: "#e0e0e0",
        },
        sidebar: {
          overview: "GENEL BAKIŞ",
          app: "Uygulama",
          commerce: "Ticaret",
          files: "Dosyalar",
          calendar: "Takvim",
          managment: "Yönetim",
          list: "Liste",
          create: "Yaratmak",
          400: "#f2f0f0",
          500: "#141b2d",
          600: "#434957",
          700: "#727681",
          800: "#a1a4ab",
          900: "#d0d1d5",
        },
        setting: {
          setting: "Ayarlar",
          mode: "Mod",
          contrast: "Zıtlık",
          direction: "Yön",
          layout: "Düzen",
          stretch: "Uzatmak",
          presets: "Ön ayarlar",
          api: "API'si",
          local: "Yerel",
          global: "Küresel",
          fullscreen: "Tam ekran",
        },
        song: {
          song: "Song",
          name: "Name",
          singer: "Singer",
          lyrics: "Lyrics",
          image: "Image",
          category: "Category",
          playlist: "Playlist",
          album: "Album",
          tags: "Tags",
          view: "View",
          comment: "Comment",
          published: "Published",
          normal: "Normal",
          yourWork: "Your Work",
          remember: "Remember",
        },
        loginPage: {
          left: "Merhaba, tekrar hoş geldiniz",
          rightTop: "Kurdsong'da oturum açın",
          rightBottom: "Hesabınıza devam edin",
          inputOwn: "E-posta adresi",
          inputTwo: "Şifre",
          button: "Giriş yapmak",
        },
      }
    : {
        user: {
          admin: "مدیر",
          manager: "تنظیم کننده",
          user: "کاربر",
          400: "#858585",
          500: "#666666",
          600: "#525252",
          700: "#3d3d3d",
          800: "#292929",
          900: "#141414",
        },
        sidebar: {
          overview: "نمای کلی",
          app: "برنامه",
          commerce: "تجارت",
          files: "فایل ها",
          calendar: "تقویم",
          managment: "مدیریت",
          list: "فهرست",
          create: "ایجاد",
          800: "#080b12",
          900: "#040509",
        },
        setting: {
          setting: "Settings",
          mode: "Mode",
          contrast: "Contrast",
          direction: "Direction",
          layout: "Layout",
          stretch: "Stretch",
          presets: "Presets",
          api: "API",
          local: "Local",
          global: "Global",
          fullscreen: "Fullscreen",
        },
        song: {
          song: "آهنگ",
          name: "نام",
          singer: "خواننده",
          lyrics: "متن",
          image: "تصویر",
          category: "دسته بندی",
          playlist: "لیست پخش",
          album: "آلبوم",
          tags: "برچسب ها",
          view: "بازدید",
          comment: "نظرات",
          published: "منتشر شد",
          normal: "عادی",
          yourWork: "کار شما",
          remember: "سفارشی",
        },
        loginPage: {
          left: "سلام، خوش آمدید",
          rightTop: "وارد کوردسونگ شوید",
          rightBottom: "به اکانت خود ادامه دهید",
          inputOwn: "آدرس ایمیل",
          inputTwo: "رمز عبور",
          button: "وارد شوید",
        },
      }),
});

export const languageSetting = (mode) => {
  const language = tokens(mode);
  return {
    user: {
      admin: language.user["admin"],
      manager: language.user["manager"],
      user: language.user["user"],
    },
    sidebar: {
      overview: language.sidebar["overview"],
      app: language.sidebar["app"],
      commerce: language.sidebar["commerce"],
      files: language.sidebar["files"],
      calendar: language.sidebar["calendar"],
      managment: language.sidebar["managment"],
      list: language.sidebar["list"],
      create: language.sidebar["create"],
    },
    setting: {
      setting: language.setting["setting"],
      mode: language.setting["mode"],
      contrast: language.setting["contrast"],
      direction: language.setting["direction"],
      layout: language.setting["layout"],
      stretch: language.setting["stretch"],
      presets: language.setting["presets"],
      api: language.setting["api"],
      local: language.setting["local"],
      global: language.setting["global"],
      fullscreen: language.setting["fullscreen"],
    },
    loginPage: {
      left: language.loginPage["left"],
      rightTop: language.loginPage["rightTop"],
      rightBottom: language.loginPage["rightBottom"],
      inputOwn: language.loginPage["inputOwn"],
      inputTwo: language.loginPage["inputTwo"],
      button: language.loginPage["button"],
    },
    song: {
      song: language.song["song"],
      name: language.song["name"],
      singer: language.song["singer"],
      lyrics: language.song["lyrics"],
      image: language.song["image"],
      category: language.song["category"],
      playlist: language.song["playlist"],
      album: language.song["album"],
      tags: language.song["tags"],
      view: language.song["view"],
      comment: language.song["comment"],
      published: language.song["published"],
      normal: language.song["normal"],
      yourWork: language.song["yourWork"],
      remember: language.song["remember"],
    },
  };
};
export const useMode = () => {
  const language = useSelector((state) => state.languageReducer.language);
  const Language = useMemo(() => languageSetting(language), [language]);

  return Language;
};
export default useMode;
